### ISSUE TITLE
Exported IOF XML 3.0 is missing geographic coordinates when OpenOrienteering Mapper map file is used

### ISSUE THREAD

**Issue by krticka** [petergolde/PurplePen#6]
When exporting IOF XML 3.0, the Purple Pen is producing different IOF XML files depending on map file format. 
1) With georeferenced map file created in OpenOrienteering Mapper (OOM) XML is missing geographic coordinates
2) With the same file but saved in Ocad12 XML contains geographic coordinates

This difference means, that OOM map file is not possible to use directly when you want export XML for the other apps where georeferencing information is required (like UsynligO).

Workaround: Map file must be first saved as Ocad12 and than used in Purple Pen. 

Tested under:
Purple Pen 3.3.0
OpenOrienteering Mapper 0.9.3, 0.9.4

[testXML.zip](https://github.com/petergolde/PurplePen/files/5548824/testXML.zip)

**Comment by petergolde** [comment]
Please email the OOM file to "peter@golde.org". I cannot debug the issue without the OOM file. Thank you for your report!

**Comment by petergolde** [comment]
Fixed in 3.4.1.
